### ISSUE TITLE
Feature: Re-add old statistics from original Karl

### ISSUE THREAD

**Issue by Darthmaul** [drg-tools/karl.gg#252]
We need to re-add the loadout data which were being provided alongside the old builder. This included the "at-a-glance" view of what was changing as you clicked on mods etc.

This was all "manually" calculated as it was hardcoded previously. We should determine the best path forward and try to re-add this information soon!

### Task List

- [x] Re-implement the statistics
- [x] Test for all base weapons
- [x] Stage test with new weapons
- [ ] Reformat build metrics to collapsible section, with a scrollable height.

**Comment by chaseconey** [comment]
Original stats component if we want to pull some inspiration
https://github.com/drg-tools/karl.gg/blob/28b087b338/resources/js/components/StatsDisplay.vue

**Comment by Darthmaul** [comment]
As a note, we should be sure to keep the existing build metrics card in a more "collapsible" div. We can re-use the preview description viewer toggle, and then also I would recommend constraining that div to a scrollable height.
